### ISSUE TITLE
One of my leg trackers seems to think it's a waist tracker even after specifying it's a leg tracker

### ISSUE THREAD

**Issue by NotMek** [ju1ce/April-Tag-VR-FullBody-Tracker#27]
Yes, I'm using the correct tracking images. Not sure what else I should do, I've re calibrated everything as well as going into the tracker management for steamvr and set them to foot left and foot right.

**Comment by ju1ce** [comment]
What do you use for a waist tracker? In vrchat, only using leg trackers is unsupported and will default to hip only trackng, which could be the problem you are describing.

In that case, either use owotrack or the virtual hip ( virtual hip/virtualhip_hmdonly.exe ) to get tracking working with only 2 apriltag trackers.

**Comment by NotMek** [comment]
I was using the virtual hip and I still had this problem. I was only trying to track my legs not my waist.

**Comment by NotMek** [comment]
And still, in SteamVR it would place one of the trackers near my waist even after calibrating it multiple times and placing them both properly where my legs are, in the april tag software it would also show that the tracker was spazing out in the air instead of being calibrated to my leg. It was only doing this with one of them, I had good lighting and the camera had a good view of the trackers

**Comment by ju1ce** [comment]
thats weird... maybe you can come into the discord and share some images/videos so i can better see what is going on?

**Comment by NotMek** [comment]
sure

**Comment by ju1ce** [comment]
Vrchat now supports only leg trackers, but it can cause the described issue. Usually, its just because the trackers are too high on the avatar and get bound to the wrong place, because avatars can often have way too long legs.

The solution would be to use avatars with legs of correct proportions, or a simpler solution that often works is to use height calibration instead of wingspan calibration, should be under IK 2.0 setttings in vrchat.
