### ISSUE TITLE
Tracking isnt consistent 

### ISSUE THREAD

**Issue by iCacko** [ju1ce/April-Tag-VR-FullBody-Tracker#77]
So I've gotten it to work, but the big issue is it's not capable of tracking movement. Slight movement makes it lose tracking or straight up makes the trackers unnoticeable. If I move my foot from point a to point b the transition isn't linear, it's more like a teleport. Then the tracker well, untracks. I'm using a 720p 30 fps webcam.

**Comment by ju1ce** [comment]
This is usualy due to motion blur that occurs when the cameras exposure setting is set too high. To fix it, you want to set its exposure manualy.

You want it to be at least at -7, and you will probably also have to increase gain or the image will be too dark.

Some more information is also available on the wiki [here](https://github.com/ju1ce/April-Tag-VR-FullBody-Tracker/wiki/Connecting-a-camera#usb-webcam-specific-parameters).
